export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const SHOW_MOVIE_DETAILS = 'SHOW_MOVIE_DETAILS';
export const HIDE_MOVIE_DETAILS = 'HIDE_MOVIE_DETAILS';

export const TOGGLE_ADD_MOVIE_POPUP = 'TOGGLE_ADD_MOVIE_POPUP';

export const SHOW_EDIT_MOVIE_POPUP = 'SHOW_EDIT_MOVIE_POPUP';
export const HIDE_EDIT_MOVIE_POPUP = 'HIDE_EDIT_MOVIE_POPUP';

export const SHOW_DELETE_MOVIE_POPUP = 'SHOW_DELETE_MOVIE_POPUP';
export const HIDE_DELETE_MOVIE_POPUP = 'HIDE_DELETE_MOVIE_POPUP';

export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const SORT = 'SORT';
export const SEARCH = 'SEARCH';
